Traceback (most recent call last):
  File "ar5_project_glaciersfair.py", line 245, in <module>
    ar5_project_glaciersfair(args.seed, args.pyear_start, args.pyear_end, args.pyear_step, args.nmsamps, args.ntsamps, args.nsamps, args.pipeline_id)
  File "ar5_project_glaciersfair.py", line 168, in ar5_project_glaciersfair
    year_var[:] = targyears
  File "src/netCDF4/_netCDF4.pyx", line 4903, in netCDF4._netCDF4.Variable.__setitem__
  File "/home/rk509/.conda/envs/conda-entk/lib/python3.7/site-packages/netCDF4/utils.py", line 356, in _StartCountStride
    datashape = broadcasted_shape(shape, datashape)
  File "/home/rk509/.conda/envs/conda-entk/lib/python3.7/site-packages/netCDF4/utils.py", line 964, in broadcasted_shape
    return np.broadcast(a, b).shape
ValueError: shape mismatch: objects cannot be broadcast to a single shape
usage: ar5_postprocess_glaciersfair.py [-h] [--locationfile LOCATIONFILE]
                                       [--pipeline_id PIPELINE_ID]
ar5_postprocess_glaciersfair.py: error: unrecognized arguments: --chunksize 662
mv: cannot stat ‘*localsl*’: No such file or directory
