tlm_fit_oceandynamics.py:209: RuntimeWarning: invalid value encountered in true_divide
  OceanDynTECorr = corr_num / corr_denom
Traceback (most recent call last):
  File "tlm_postprocess_oceandynamics.py", line 265, in <module>
    tlm_postprocess_oceandynamics(args.nsamps, args.seed, args.chunksize, args.keep_temp, args.pipeline_id)
  File "tlm_postprocess_oceandynamics.py", line 186, in tlm_postprocess_oceandynamics
    combined = xr.open_mfdataset("{0}_tempsamps_*.nc".format(pipeline_id), concat_dim="locations", chunks={"locations":chunksize})
  File "/home/rk509/.conda/envs/conda-entk/lib/python3.7/site-packages/xarray/backends/api.py", line 889, in open_mfdataset
    "When combine='by_coords', passing a value for `concat_dim` has no "
ValueError: When combine='by_coords', passing a value for `concat_dim` has no effect. To manually combine along a specific dimension you should instead specify combine='nested' along with a value for `concat_dim`.
mv: cannot stat ‘*localsl*’: No such file or directory
